FROM ruby:2.7.2-alpine

ENV LANG ru_RU.UTF-8
ENV LANGUAGE ru_RU:ru
ENV LC_LANG ru_RU.UTF-8
ENV LC_ALL ru_RU.UTF-8

RUN apk add coreutils gcc g++ libc-dev libstdc++ make git imagemagick ffmpeg postgresql-dev nodejs tzdata

WORKDIR /app

COPY Gemfile Gemfile.lock /app/
RUN bundle
