---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/health":
    get:
      summary: Return server status
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  "/weather/current":
    get:
      summary: Return current temperature
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  time:
                    type: string
                  temperature:
                    type: number
                required:
                - time
                - temperature
  "/weather/historical":
    get:
      summary: Return last 24 temperature
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    time:
                      type: string
                    temperature:
                      type: number
                  required:
                  - time
                  - temperature
  "/weather/historical/max":
    get:
      summary: Return the maximum temperature for the last 24 hours
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  time:
                    type: string
                  temperature:
                    type: number
                required:
                - time
                - temperature
  "/weather/historical/min":
    get:
      summary: Return the minimum temperature for the last 24 hours
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  time:
                    type: string
                  temperature:
                    type: number
                required:
                - time
                - temperature
  "/weather/historical/avg":
    get:
      summary: Return the average temperature for the last 24 hours
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: number
  "/weather/by_time":
    parameters:
    - name: unix_time
      in: query
      description: date from client
      schema:
        type: string
    get:
      summary: Return temperature by time
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  time:
                    type: string
                  temperature:
                    type: number
                required:
                - time
                - temperature
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
