---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/health":
    get:
      summary: Return server status
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  "/weather/current":
    get:
      summary: Return current temperature
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  time:
                    type: number
                  temperature:
                    type: number
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
