development:
  :concurrency: 1
:queues:
  - default
# :max_retries: 10

:schedule:
  run_now:
    in: 0s   # Runs now
    class: ActualizeWeatherJob
    description: "Run now. Actualize temperature when the application starts"

  check_every_hour:
    # cron: '0 0 * * * *'   # Runs once per 1 hour
    cron: '*/5 * * * * *'   # Runs once per 1 hour
    class: CheckWeatherJob
    description: "Runs every hour. Actualize temperature"
